ARG UBI_IMAGE=registry.access.redhat.com/ubi10/ubi:10.0
ARG UBI_IMAGE_MICRO=registry.access.redhat.com/ubi10/ubi-micro:10.0

FROM ${UBI_IMAGE_MICRO} AS target

# We don't have to start from scratch and repeate the ubi9 installation
# Just copy the ubi9 image created and add new packages
FROM ${UBI_IMAGE} AS build

ARG DNF_INSTALL_ROOT="/mnt/rootfs"
ARG DNF_OPTS="--setopt install_weak_deps=false --nodocs"
ARG DNF_OPTS_ROOT="-y --installroot ${DNF_INSTALL_ROOT}"
ARG PACKAGES="python3.12"

RUN mkdir -p ${DNF_INSTALL_ROOT}
COPY --from=target / ${DNF_INSTALL_ROOT}/

RUN dnf ${DNF_OPTS_ROOT} ${DNF_OPTS} install ${PACKAGES} && \
    dnf ${DNF_OPTS_ROOT} clean all && \
    rm -rf ${DNF_INSTALL_ROOT}/var/cache/* ${DNF_INSTALL_ROOT}/var/log/dnf* ${DNF_INSTALL_ROOT}/var/log/yum.*

WORKDIR /app

RUN dnf install -y ${PACKAGES}

RUN --mount=from=ghcr.io/astral-sh/uv,source=/uv,target=/bin/uv \
--mount=type=cache,target=/root/.cache/uv \
--mount=type=bind,source=uv.lock,target=uv.lock \
--mount=type=bind,source=pyproject.toml,target=pyproject.toml \
uv sync --locked --no-editable

# Changing ownership and user rights to support following use-cases:
# 1) running container on OpenShift, whose default security model
#    is to run the container under random UID, but GID=0
# 2) for working root-less container with UID=1001, which does not have
#    to have GID=0
# 3) for default use-case, that is running container directly on operating system,
#    with default UID and GID (1001:0)
# Supported combinations of UID:GID are thus following:
# UID=1001 && GID=0
# UID=<any>&& GID=0
# UID=1001 && GID=<any>
FROM scratch

ARG DNF_INSTALL_ROOT="/mnt/rootfs"

COPY --from=build --chown=1001:0 /app /app
COPY --from=build ${DNF_INSTALL_ROOT}/ /

RUN chmod -R g+rx /app/.venv

USER 1001

ENV PATH="/app/.venv/bin:$PATH"
# Replace with your MCP server command; example: uvx mcp-server-time
CMD ["/app/.venv/bin/mcpo"]